# routes/docx_report.py

import io
from datetime import datetime
from bson import ObjectId
from fastapi import APIRouter, HTTPException, Depends
from fastapi.responses import StreamingResponse
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT

from db import require_db
from routes.auth import get_current_user

router = APIRouter(prefix="/api/scan", tags=["docx-report"])

SEVERITY_COLORS = {
    "critical": RGBColor(0xDC, 0x26, 0x26),
    "major": RGBColor(0xEA, 0x58, 0x0C),
    "minor": RGBColor(0xCA, 0x8A, 0x04),
    "needs_review": RGBColor(0x93, 0x33, 0xEA),
}


def _build_docx(scan, violations):
    doc = Document()

    style = doc.styles["Normal"]
    style.font.size = Pt(10)

    title = doc.add_heading("Legal Metrology Compliance Report", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_paragraph(f"Generated: {datetime.utcnow().strftime('%d %b %Y, %H:%M UTC')}")
    doc.add_paragraph("")

    overall = scan.get("overall_status", "unknown")
    p = doc.add_paragraph()
    run = p.add_run(f"Overall Status: {overall.upper()}")
    run.bold = True
    if overall == "compliant":
        run.font.color.rgb = RGBColor(0x16, 0xA3, 0x4A)
    else:
        run.font.color.rgb = RGBColor(0xDC, 0x26, 0x26)

    doc.add_heading("Product Information", level=1)
    fields = scan.get("extracted_fields", {})
    field_rows = [
        ("Product Name", fields.get("commodity_name", "—")),
        ("Manufacturer", fields.get("manufacturer_name", "—")),
        ("Address", fields.get("manufacturer_address", "—")),
        ("MRP", fields.get("mrp", "—")),
        ("Net Quantity", fields.get("net_quantity", "—")),
        ("Manufacture Date", fields.get("manufacture_date", "—")),
        ("Best Before", fields.get("best_before", "—")),
        ("Consumer Care Phone", fields.get("consumer_care_phone", "—")),
        ("Consumer Care Email", fields.get("consumer_care_email", "—")),
        ("Country of Origin", fields.get("country_of_origin", "—")),
        ("Language", fields.get("language", "—")),
    ]
    table = doc.add_table(rows=len(field_rows) + 1, cols=2)
    table.style = "Light Grid Accent 1"
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    hdr = table.rows[0].cells
    hdr[0].text = "Field"
    hdr[1].text = "Value"
    for i, (label, value) in enumerate(field_rows, 1):
        table.rows[i].cells[0].text = label
        table.rows[i].cells[1].text = str(value)

    summary = scan.get("violations_summary", {})
    if summary:
        doc.add_heading("Violations Summary", level=1)
        s_table = doc.add_table(rows=2, cols=5)
        s_table.style = "Light Grid Accent 1"
        for j, header in enumerate(["Critical", "Major", "Minor", "Needs Review", "Total"]):
            s_table.rows[0].cells[j].text = header
        for j, key in enumerate(["critical", "major", "minor", "needs_review", "total"]):
            s_table.rows[1].cells[j].text = str(summary.get(key, 0))

    if violations:
        doc.add_heading("Violation Details", level=1)
        v_table = doc.add_table(rows=len(violations) + 1, cols=4)
        v_table.style = "Light Grid Accent 1"
        v_hdr = v_table.rows[0].cells
        v_hdr[0].text = "Rule"
        v_hdr[1].text = "Field"
        v_hdr[2].text = "Severity"
        v_hdr[3].text = "Message"
        for i, v in enumerate(violations, 1):
            v_table.rows[i].cells[0].text = v.get("rule_id", "")
            v_table.rows[i].cells[1].text = v.get("field", "")
            sev = v.get("severity", "")
            cell = v_table.rows[i].cells[2]
            cell.text = sev
            for run in cell.paragraphs[0].runs:
                run.font.color.rgb = SEVERITY_COLORS.get(sev, RGBColor(0, 0, 0))
            v_table.rows[i].cells[3].text = v.get("message", "")
    else:
        doc.add_paragraph("No violations found — product is compliant.")

    doc.add_paragraph("")
    doc.add_paragraph(
        "This report was generated by the Legal Metrology Compliance Checker. "
        "For official use only."
    ).italic = True

    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf


@router.get("/{scan_id}/report/docx")
def generate_docx_report(scan_id: str, current_user=Depends(get_current_user)):
    db = require_db()
    scan = db.scans.find_one({"_id": ObjectId(scan_id)})
    if not scan:
        raise HTTPException(status_code=404, detail="Scan not found")

    violation_ids = scan.get("violations", [])
    violations = []
    if isinstance(violation_ids, list) and violation_ids:
        violations = list(db.violations.find({"_id": {"$in": violation_ids}}))

    docx_buf = _build_docx(scan, violations)

    return StreamingResponse(
        docx_buf,
        media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        headers={
            "Content-Disposition": f'attachment; filename="compliance-report-{scan_id}.docx"'
        },
    )
